name: Build iOS App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Instalar Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Instalar dependencias
      run: flutter pub get

    # --- NUEVO PASO PARA CREAR EL ARCHIVO SECRETO ---
    - name: Crear archivo strava_secrets.dart
      run: |
        mkdir -p lib/core/strava
        echo "const String stravaClientId = '${{ secrets.STRAVA_CLIENT_ID }}';" > lib/core/strava/strava_secrets.dart
        echo "const String stravaClientSecret = '${{ secrets.STRAVA_CLIENT_SECRET }}';" >> lib/core/strava/strava_secrets.dart
    # --------------------------------------------------

    - name: Compilar iOS (sin firma)
      run: flutter build ios --release --no-codesign

    - name: Empaquetar a .ipa
      run: |
        mkdir Payload
        mv build/ios/iphoneos/Runner.app Payload/
        zip -r RowMate.ipa Payload

    - name: Subir el .ipa para descargar
      uses: actions/upload-artifact@v4
      with:
        name: RowMate-App
        path: RowMate.ipa